package trial

import (
	"fmt"
	"os"
	"strconv"
)

func GenerateCandidatePhase(candidatePath, outputPath string) error {
	var candidate CandidateBundle
	if err := ReadJSON(candidatePath, &candidate); err != nil {
		return err
	}
	if candidate.Decision != "CLOSED" || !candidate.SemanticGraphDelta.ExactPair || !candidate.RollbackDelta.ExactPair {
		return fmt.Errorf("delta candidate is not an exact closed candidate")
	}
	if candidate.Counts.AddedCells != 2 || candidate.Counts.RetiredCells != 1 || candidate.Counts.SplitCells != 1 {
		return fmt.Errorf("delta candidate is not the required one-to-two split: added=%d retired=%d split=%d", candidate.Counts.AddedCells, candidate.Counts.RetiredCells, candidate.Counts.SplitCells)
	}
	if len(candidate.SemanticGraphDelta.AddedCells) != 2 || len(candidate.SemanticGraphDelta.RetiredCells) != 1 || len(candidate.SemanticGraphDelta.SplitCells) != 1 {
		return fmt.Errorf("delta candidate split payload is incomplete")
	}
	if len(candidate.SemanticGraphDelta.SplitCells[0].AddedCellIDs) != 2 {
		return fmt.Errorf("delta candidate split does not contain two added cells")
	}
	content := "package reflexive\nnamespace reflexive\n\n"
	content += "entity SourceGraph id \"gooo://reflexive/compiler/source-graph\"\n"
	content += "entity ParsedSource id \"gooo://reflexive/compiler/parsed-source\"\n"
	content += "entity SemanticIR id \"gooo://reflexive/compiler/semantic-ir\"\n"
	content += "entity GeneratedBackend id \"gooo://reflexive/compiler/generated-backend\"\n"
	content += "entity Evidence id \"gooo://reflexive/compiler/evidence\"\n\n"
	content += "# Generated by the Gooo metacode evolution loop from candidate-bundle.json.\n"
	content += "# candidate_digest=" + candidate.CandidateDigest + " delta_digest=" + candidate.DeltaDigest + "\n"
	content += "# retired_cell=" + candidate.SemanticGraphDelta.RetiredCells[0].ID + " added_cells=" + candidate.SemanticGraphDelta.AddedCells[0].ID + "+" + candidate.SemanticGraphDelta.AddedCells[1].ID + "\n"
	content += "activity ParseSource(SourceGraph) -> ParsedSource computes " + strconv.Quote("reflexive.normalize:v1;input=GOOO;declarations=entity,activity;stable_id=declared-or-namespace-activity-name;normal_form=sort-by-stable-id;duplicate=REFUTED;missing=UNKNOWN;required_entity=gooo://reflexive/input/required;split=ParseSource+ValidateStableIDs") + "\n"
	content += "activity ValidateStableIDs(ParsedSource) -> SemanticIR computes " + strconv.Quote("reflexive.validate-stable-ids:v1;input=PARSED_SOURCE;duplicate=REFUTED;missing=UNKNOWN") + "\n"
	content += "activity EmitBackend(SemanticIR) -> GeneratedBackend computes " + strconv.Quote("reflexive.backend-go:v1;authority=SOURCE_GOOO_GRAPH;artifact=BACKEND_ONLY;binding=semantic-ir") + "\n"
	content += "activity VerifyReplay(SemanticIR) -> Evidence computes " + strconv.Quote("reflexive.replay:v1;input=GENERATED_SEMANTIC_IR;compare=CANONICAL_DIGEST;rollback=RETAIN_BASELINE") + "\n"
	if err := os.MkdirAll(outputDir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, []byte(content), 0o644)
}

func outputDir(path string) string {
	for index := len(path) - 1; index >= 0; index-- {
		if path[index] == '/' {
			if index == 0 {
				return "/"
			}
			return path[:index]
		}
	}
	return "."
}
